//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web
{
    public partial class DefaultPage
    {
        protected global::System.Web.UI.WebControls.Content Content1;
    }
}
