//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlTitle PageTitle;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.HtmlControls.HtmlForm MainForm;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;
    }
}
