//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Badges
{
    public partial class Index
    {
        protected global::System.Web.UI.WebControls.Repeater rptBadges;
    }
}
