//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Badges
{
    public partial class Leaderboard
    {
        protected global::System.Web.UI.WebControls.Panel pnlUserRank;
        protected global::System.Web.UI.WebControls.Literal litUserRank;
        protected global::System.Web.UI.WebControls.Repeater rptLeaderboard;
    }
}
