//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Progress
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litXp;
        protected global::System.Web.UI.WebControls.Literal litStreak;
        protected global::System.Web.UI.WebControls.Literal litBadges;
        protected global::System.Web.UI.WebControls.Literal litNoCourses;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}
