//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Courses
{
    public partial class LessonPage
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlLesson;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor aCourse;
        protected global::System.Web.UI.WebControls.Literal litModuleName;
        protected global::System.Web.UI.WebControls.Literal litLessonTitle;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Panel pnlVideo;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl videoSrc;
        protected global::System.Web.UI.WebControls.Panel pnlNotes;
        protected global::System.Web.UI.WebControls.Literal litNoteContent;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor aNoteFile;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
        protected global::System.Web.UI.WebControls.Button btnMarkComplete;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor aNext;
    }
}
