//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Courses
{
    public partial class QuizPage
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litPassing;
        protected global::System.Web.UI.WebControls.HiddenField hfQuizId;
        protected global::System.Web.UI.WebControls.HiddenField hfAttemptId;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.WebControls.Literal litScore;
        protected global::System.Web.UI.WebControls.Literal litResultMsg;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor aBack;
    }
}
