<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AaramEducation.Core\AaramEducation.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="MySql.Data" Version="8.0.33" />
    <PackageReference Include="MySql.Data.EntityFramework" Version="8.0.33" />
  </ItemGroup>
</Project>
