//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Account
{
    public partial class LoginPage
    {
        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;
        protected global::System.Web.UI.WebControls.CheckBox chkRemember;
        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
