// Regenerates *.aspx.designer.cs / *.Master.designer.cs from markup.
// Visual Studio normally owns these files; this project has no working WebForms
// tooling, so run this after editing control IDs in any .aspx/.Master.
//   bun tools/gen-aspx-designer.ts [--check]

import { Glob } from "bun";

const WEB_ROOT = new URL("../src/AaramEducation.Web/", import.meta.url).pathname;
const checkOnly = process.argv.includes("--check");

// Controls declared inside an ITemplate live in a child naming container, so the
// runtime never assigns them to a page field. VS omits them; so do we.
const TEMPLATES = new Set([
  "itemtemplate", "alternatingitemtemplate", "headertemplate", "footertemplate",
  "separatortemplate", "edititemtemplate", "insertitemtemplate", "emptydatatemplate",
  "layouttemplate", "selecteditemtemplate", "grouptemplate", "pagertemplate",
  "emptyitemtemplate", "contenttemplate",
]);

const HTML_CONTROLS: Record<string, string> = {
  a: "HtmlAnchor", form: "HtmlForm", head: "HtmlHead", title: "HtmlTitle",
  link: "HtmlLink", meta: "HtmlMeta", img: "HtmlImage", select: "HtmlSelect",
  textarea: "HtmlTextArea", table: "HtmlTable", tr: "HtmlTableRow",
  td: "HtmlTableCell", th: "HtmlTableCell", button: "HtmlButton",
  iframe: "HtmlIframe", input: "HtmlInputGenericControl",
};

const TAG =
  /<(\/?)([A-Za-z][\w:.-]*)((?:\s+[\w:.-]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s"'>]+))?)*)\s*(\/?)>/g;
const ATTR = /([\w:.-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))/g;
const VOID_HTML = new Set([
  "area", "base", "br", "col", "embed", "hr", "img", "input",
  "link", "meta", "param", "source", "track", "wbr",
]);

function attrs(raw: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const m of raw.matchAll(ATTR)) {
    out[m[1].toLowerCase()] = m[2] ?? m[3] ?? m[4] ?? "";
  }
  return out;
}

function clrType(tag: string): string {
  if (tag.toLowerCase().startsWith("asp:")) {
    return `System.Web.UI.WebControls.${tag.slice(4)}`;
  }
  const html = HTML_CONTROLS[tag.toLowerCase()] ?? "HtmlGenericControl";
  return `System.Web.UI.HtmlControls.${html}`;
}

function parse(source: string) {
  const directive = source.match(/<%@\s*(Page|Master|Control)\b[\s\S]*?%>/i)?.[0];
  if (!directive) return null;
  const inherits = directive.match(/Inherits\s*=\s*"([^"]+)"/i)?.[1];
  if (!inherits) return null;

  // Strip server comments and inline code so their contents never look like tags.
  const markup = source
    .replace(/<%--[\s\S]*?--%>/g, "")
    .replace(/<%[\s\S]*?%>/g, "");

  const controls: { id: string; type: string }[] = [];
  const seen = new Set<string>();
  const open: string[] = [];
  let templateDepth = 0;

  for (const m of markup.matchAll(TAG)) {
    const [, closing, tag, rawAttrs, selfClose] = m;
    const lower = tag.toLowerCase();
    const isTemplate = TEMPLATES.has(lower);
    const selfClosed = selfClose === "/" || (!tag.includes(":") && VOID_HTML.has(lower));

    if (closing === "/") {
      if (isTemplate && templateDepth > 0) templateDepth--;
      const at = open.lastIndexOf(lower);
      if (at !== -1) open.length = at;
      continue;
    }

    if (templateDepth === 0 && !isTemplate) {
      const a = attrs(rawAttrs);
      const id = a["id"];
      const isServer = lower.startsWith("asp:") || a["runat"]?.toLowerCase() === "server";
      // No ID means the runtime auto-names it and no field is ever assigned.
      if (id && isServer && !seen.has(id)) {
        seen.add(id);
        controls.push({ id, type: clrType(tag) });
      }
    }

    if (!selfClosed) {
      if (isTemplate) templateDepth++;
      else open.push(lower);
    }
  }

  const dot = inherits.lastIndexOf(".");
  return {
    ns: dot === -1 ? null : inherits.slice(0, dot),
    cls: dot === -1 ? inherits : inherits.slice(dot + 1),
    controls,
  };
}

function render(ns: string | null, cls: string, controls: { id: string; type: string }[]) {
  const indent = ns ? "        " : "    ";
  const fields = controls
    .map((c) => `${indent}protected global::${c.type} ${c.id};`)
    .join("\n");
  const body =
    `${ns ? "    " : ""}public partial class ${cls}\n` +
    `${ns ? "    " : ""}{\n${fields}${fields ? "\n" : ""}${ns ? "    " : ""}}`;

  return (
    `//------------------------------------------------------------------------------\n` +
    `// <auto-generated>\n` +
    `//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.\n` +
    `// </auto-generated>\n` +
    `//------------------------------------------------------------------------------\n` +
    `\n#nullable disable\n\n` +
    (ns ? `namespace ${ns}\n{\n${body}\n}\n` : `${body}\n`)
  );
}

const pages = new Glob("**/*.{aspx,ascx,Master,master}");
let written = 0;
const stale: string[] = [];

for await (const rel of pages.scan({ cwd: WEB_ROOT })) {
  if (rel.startsWith("bin/") || rel.startsWith("obj/")) continue;

  const parsed = parse(await Bun.file(WEB_ROOT + rel).text());
  if (!parsed) {
    console.warn(`skip  ${rel} (no Inherits= directive)`);
    continue;
  }

  const target = `${WEB_ROOT}${rel}.designer.cs`;
  const next = render(parsed.ns, parsed.cls, parsed.controls);
  const prev = await Bun.file(target).exists()
    ? await Bun.file(target).text()
    : null;

  if (prev === next) continue;
  if (checkOnly) {
    stale.push(rel);
    continue;
  }

  await Bun.write(target, next);
  written++;
  console.log(`write ${rel}.designer.cs  (${parsed.controls.length} controls)`);
}

if (checkOnly && stale.length) {
  console.error(`designer files out of date:\n  ${stale.join("\n  ")}`);
  process.exit(1);
}
console.log(checkOnly ? "designer files up to date" : `\n${written} file(s) written`);
