//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Tutor
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}
