//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Tutor
{
    public partial class LessonForm
    {
        protected global::System.Web.UI.WebControls.Literal litHeading;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.HiddenField hdnLessonId;
        protected global::System.Web.UI.WebControls.HiddenField hdnModuleId;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtOrder;
        protected global::System.Web.UI.WebControls.CheckBox chkFreeSample;
        protected global::System.Web.UI.WebControls.HiddenField hdnVideoId;
        protected global::System.Web.UI.WebControls.TextBox txtVideoTitle;
        protected global::System.Web.UI.WebControls.TextBox txtVideoUrl;
        protected global::System.Web.UI.WebControls.HiddenField hdnNoteId;
        protected global::System.Web.UI.WebControls.TextBox txtNoteTitle;
        protected global::System.Web.UI.WebControls.TextBox txtNoteContent;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.HyperLink lnkCancel;
    }
}
