//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Tutor
{
    public partial class ManageCourse
    {
        protected global::System.Web.UI.WebControls.Literal litCourseName;
        protected global::System.Web.UI.WebControls.HyperLink lnkNewModule;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Repeater rptModules;
    }
}
