//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Notifications
{
    public partial class NotificationsIndexPage
    {
        protected global::System.Web.UI.WebControls.Content Content1;
        protected global::System.Web.UI.WebControls.Button btnMarkAll;
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
    }
}
