//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Admin
{
    public partial class CoursesAdminPage
    {
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}
