//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by tools/gen-aspx-designer.ts. Changes will be overwritten.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AaramEducation.Web.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litUsers;
        protected global::System.Web.UI.WebControls.Literal litCourses;
        protected global::System.Web.UI.WebControls.Literal litEnrollments;
        protected global::System.Web.UI.WebControls.Literal litPending;
    }
}
